### ISSUE TITLE
2020-12 POJ1941：The Sierpinski Fractal - 解题报告（吴泰维）

### ISSUE THREAD

**Issue by zetawu** [CSGrandeur/s-1problem1day1ac#1]
### 题目大意
谢尔宾斯基三角形的做法如下：将一个三角形三条边的中点相连，使该三角形被分割为四个相同大小的小三角形，并去掉中间部分的小三角形，这就得到了维度为2的谢尔宾斯基三角形。对于剩下的三个小三角形分别再次进行该操作，则得到了维度为3的谢尔宾斯基三角形。本题给定了多个数字n，要求算打印出n维的谢尔宾斯基三角形。每个谢尔宾斯基三角形中，最小的三角形都应如下图所示：
![](https://s3.jpg.cm/2020/11/30/srcdt.png)

### 解题思路
原题目中对于谢尔宾斯基三角形的描述为, "Consider a regular triangular area, divide it into four equal triangles of half height and remove the one in the middle. Apply the same operation recursively to each of the three remaining triangles."，意为“将一个三角形区域分割为相同大小的四个三角形，使他们的高长为原三角形区域的一半。去掉中间的小三角形，并递归地对剩下的三个三角形实施同样的操作。”
这其实已经明示了让我们使用递归来解题。我们干脆顺着题目的思路，使用递归解决此问题。
要解决这个问题，我们应当找到每个最小的三角形应该在的位置，并在这个位置将最小三角形打印出来。按照我们之前对题意的分析，我们可以用递归的方法找出这些位置。
我们不妨定义一个函数，它的参数包含三角形的维度，以及该三角形的位置信息。每个n维的三角形都可以认为是占用了一个矩形空间（矩形的长为三角形的底边，宽为三角形的高）。我们不妨以它们占用地矩形空间左上角端点的坐标来记录他们所在的位置信息。因此，我们需要建立一个二维的坐标系来描述这些端点的位置。这些端点的坐标记作(x, y)。这个坐标系也就是我们画三角形的画布。
最开始，我们将目标三角形的维度n传入函数中。显然，该目标的位置在坐标系的左上角，我们可以将其记作(0,0)。根据对谢尔宾斯基三角形的观察，我们不难发现，维度为n的三角形的底长为d=2^(n+1)，高长为h=2^n。我们可以据此计算出在该三角形中所构造的三个(n-1)维三角形所在矩形的左上端点坐标。
接下来，再次调用该函数，把维度(n-1)，和这三个位置信息分别传入函数中。若此时的维度(n-1)已经为1，则说明我们已经找到了最小三角形的位置，位置信息便是本次传入此函数的参数。我们应当在坐标系画布中画出此三角形。
若维度(n-1)仍不为1，说明我们仍未找到最小三角形。此时应再次调用该函数，将维度(n-2)，和三个在此三角形中产生的，维度为(n-2)的小三角形的位置信息分别传入函数中。如此往复，直至维度为1为止。

### 复杂度分析
此题中，递归算法的时间复杂度为O(n)。同时，在每次开始画三角形之前，我们都需要清空画布，以防止上一次作画留下的痕迹影响此次作画。维度为n的三角形的底长为d=2^(n+1)，高长为h=2^n。它所占用的矩形面积则为(d\*h) = 2^(2n+1)，大约值为(4^n)。因此，在清空画布时，我们会进行数量级为4^n次的运算，因此时间复杂度为 `O(4^n)`。
同时，由于我们运算时定义了大小为(d\*h)的画布，因此我们也需要定义大小为4^n的数组，所以空间复杂度也为`O(4^n)`。

### 算法资料与心得体会
这是我第一次接触画图题。关于图形的存储与输出，我参考了blog.csdn.net/weixin_40760678/article/details/100546963的做法，建立了一个数组作为画布存储图像并在完成操作后输出。相比边画边输出的方法，将图形存起来再统一输出的方法更加适合递归和递推的算法。当以后碰到类似的画图题时，我们都可以像这样，建立画布数组存储图形，统一输出。
具体的讲解我已放到了标程的注释中

### 代码
```C++
#include<iostream>
#include<cmath>
using namespace std;
char huabu[3000][3000];//画布
void hua(int x, int y, int n)
//此处的x和y表示该矩形左上角顶点的横纵坐标
{
    if(n == 1)//若此三角形为最小三角形
    {
        huabu[y][x + 1] = '/';
        huabu[y][x + 2] = '\\';//字符'\'需要用'\\'表示
        huabu[y + 1][x] = '/';
        huabu[y + 1][x + 1] = '_';
        huabu[y + 1][x + 2] = '_';
        huabu[y + 1][x + 3] = '\\';
        return;
    }
    
    int h = pow(2.0, n);//n维三角形的高长
    int d = pow(2.0, n + 1);//n维三角形的底长
    hua(x + (d / 4), y, n - 1);//画出位于原三角形区域上部的三角形，其维度为n-1，占用的矩形区域左上角顶点坐标为(x+(d/4),y)
    hua(x, y + (h / 2), n - 1);//画出位于原三角形区域左下部的三角形
    hua(x + (d / 2), y + (h / 2), n - 1);//画出位于原三角形区域右下部的三角形
}

int main()
{
    int n,i,j,d,h;
    for(;;)
    {
        cin >> n;
        if(n == 0)
            return 0;
        h = pow(2.0, n);
        d = pow(2.0, n + 1);
        
        for(i = 0; i < h; i++)
            for(j = 0; j < d; j++)
            huabu[i][j] = ' ';//清空画布。使图形中没有线条的部分被空格占满，显示出空白的效果。
            
        hua(0, 0, n);
        for(i=0; i<h; i++)
        {
            for(j = 0; j < d; j++)
                cout << huabu[i][j];
            cout << endl;
        }
        cout << endl;
    }
}
```

**Comment by SamuNatsu** [comment]
# 本人总结的几个快速确定时间复杂度的方法

### 只算循环和递归
> **大部分情况下**程序运行的时间都是由循环与递归堆积出来的，其他顺序结构可以一律按照`O(1)`，即常数时间复杂度处理
> 例如：
> 递归版斐波那契数列的时间复杂度是`O(2^n)`
> `int fib(int n) {`
> `return n <= 2 ? 1 : fib(n - 1) + fib(n - 2);`
> `}`
> 递推版斐波那契数列的时间复杂度是`O(n)`
> `for (int i = 3; i < n; ++i)`
> `fib[i] = fib[i - 1] + fib[i - 2];`
> A+B Problem的时间复杂度是`O(1)`
> `printf("%d\n", A + B);`

### 不算常数
> 当循环数量是个常数时，默认其时间复杂度为`O(1)`
> 例如：
> `for (int i = 0; i < 10; ++i) {}`

### 取大不取小
> 在顺序结构中，如果同一层的不同程序块有不同的时间复杂度，我们只取**最高阶**的那个作为整一层级的时间复杂度
> 例如：
> `{`
> `for (int i = 0; i < n; ++i) {}`
> `for (int i = 0; i < n * n; ++i) {}`
> `}`
> 在这种情况下，一个for循环时间复杂度为`O(n)`，另一个为`O(n^2)`，所以我们整个代码块的复杂度就取`O(n^2)`，因为n^2是最高阶的

### 嵌套相乘
> 在出现了带有n的嵌套循环时，整个循环的时间复杂度是每层嵌套循环的时间复杂度相乘
> 例如：
> `for (int i = 0; i < n; ++i)`
> `for (int j = 0; j < n; ++j) {}`
> 此时整个循环的时间复杂度为`O(n^2)`，就是内部循环的`O(n)`与外部循环的`O(n)`相乘

### 考虑最坏情况
> 时间复杂度使用的是大O表达法，本质上就是表示在极限（最坏）情况下的时间复杂度上界，所以在进行如递归分析和一些复杂循环分析的时候，我们应该假设该算法在最坏的情况下是如何表现的，这时候我们可以把一些循环修饰给简化上面的形式（虽然这样子可能会造成一些不严谨，但是本质考虑最差情况也是可以适当地超出真实上界的）

**Comment by CSGrandeur** [comment]
优秀！
