### ISSUE TITLE
2020-12 HDU1274：展开字符串 - 解题报告（王海宏）

### ISSUE THREAD

**Issue by whhcs** [CSGrandeur/s-1problem1day1ac#2]
### 题目大意

将写成缩写形式的字符串展开

### 解题思路

说实话，我看到这题目没想到递归，不过本周专题是递归与函数嘛，那就用递归。那么问题来了，对于我一个从没用过递归的萌新来说，老实说这题难度有点大了。所以我只好在网上搜了别人的解题思路，自己实现一遍
大概思路如下：从左边开始一个字符一个字符的判断，遇到'('则进行递归，每次记录要重复输出的次数，遇到')'递归结束，返回')'的位置，若数字后面没有'('则将数字后面的单个字符循环输出。

### 复杂度分析

递归的时间复杂度取决于数组的长度，乘上我们输入数据的规模n，所以时间复杂度为 `O(n^2)`。空间复杂度不会判断，我猜测只跟数组大小相关，所以为空间复杂度`O(n)`

### 算法资料与心得体会

这是我第一次做递归题目，以前只听过理论，递归就是函数自己调用自己嘛，不过实际遇到题目才发现我根本不知道何时用递归，以及怎样用递归（写完这篇报告之后一定恶补相关知识）。由于我紫书已经好久没翻过了，所以紫书的进度仍然停留在第三章字符串的习题那里。所以第一次面对这种题目我其实没什么思路，解题思路我参考了https://www.cnblogs.com/hxsyl/archive/2012/08/30/2663438.html
的做法，从左边开始一个字符一个字符的判断，遇到'('则进行递归，每次记录要重复输出的次数，遇到')'递归结束，返回')'的位置。心得就是以后遇到这种将某位置中的某段字符串循环多次输出，则可考虑用递归实现。同时紫书进度不能落下，等这周复习完高数之后，一定刷起来。
具体的讲解我已放到了标程的注释中

### 代码
```C++

#include<iostream>
#include<cstdio>
#include<math.h>
#include<string.h>
#include<algorithm>
#include<ctype.h>
#include<string>
using namespace std;

const int N = 300;
char a[N];                      //用于存储读取的字符串
int len;                        //获取数组a的长度
int i = 0;                      //全局变量，记录数组下标

int kk(int i)         //i表示数组a的下标
{
    int temp = 0;     //用于标记')'的位置

    for(a[i]; a[i] != ')' && i < len; i++, a[i])      //遇到')'或者字符串结束则停止递归
    {
        int num = 0;                                  //num用于记录读取到的数字大小

        while(isdigit(a[i]))                          //isdigit()判断是否为数字,一直到不是数字为止
        {
            num = num * 10 + a[i] - '0';
            i++;
        }

        if(!num)
            num = 1;                                  //若第一个字符不是数字，说明只需循环一次

        if(a[i] == '(' )
        {
            i++;                                      //从'('右边第一个字母开始递归，直到遇到')'
            while(num--)
            {
                temp = kk(i);
            }
            i = temp;                                 //用于标记')'的位置
        }
        else                                          //不是'('，那一定就是待输出的字母了，直接输出就好
        {
            while(num--)
            {
                cout.put(a[i]);                         //cout.put()输出单个字符
            }
        }
    }

    if(a[i] == ')' )
        return i;                                       //返回')'的位置
}

int main()
{
    int n;
    cin >> n;                   //n组数据

    while(n--)
    {
        memset(a, 0, sizeof(a));  //初始化数组a，没有这行也不影响
        cin >> a;
        len = strlen(a);           //获取输入字符串的长度
        kk(0);                  //调用函数从a[0]开始读取
        cout << endl;
    }

    return 0;
}

```

**Comment by 8arry** [comment]
爱了

**Comment by Mzying2001** [comment]
# 解法2

提供一种不用递归的方法 -- 当然，代码量会多一点

## 思路

将输入的字符串看成一个表达式，将其转化成[中缀表达式](https://baike.baidu.com/item/%E4%B8%AD%E7%BC%80%E8%A1%A8%E8%BE%BE%E5%BC%8F)，再转成[逆波兰表达式](https://baike.baidu.com/item/%E9%80%86%E6%B3%A2%E5%85%B0%E5%BC%8F)（即后缀表达式），利用栈来解决问题。

## 例子

以Sample Input 的第一个 `1(1a2b1(ab)1c)` 为例，将其转换成中缀表达式：

```txt
[1, *, (, 1, *, a, +, 2, *, b, +, 1, *, (, a, +, b, ), +, 1, *, c, )]
```

则其后缀表达式就为：

```txt
[1, 1, a, *, 2, b, *, 1, a, b, +, *, 1, c, *, +, +, +, *]
```

## 代码

我用的是Java，语法跟C++是差不多的...（看看有没有大佬写个C++版本<img src="https://img.wenhairu.com/images/2020/12/01/WMVWt.png" height=20 width=20 />）

```Java
import java.util.*;

public class Main {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int n = sc.nextInt();
        while (n-- > 0)
            System.out.println(calculate(sc.next()));

        sc.close();
    }

    static int operationPriority(char opera) {
        return opera == '*' ? 1 : 0;
    }

    static List<String> toInfixExpression(String expression) {
        List<String> ls = new ArrayList<>();
        char[] chars = expression.toCharArray();

        for (int i = 0; i < chars.length; i++) {
            String item = String.valueOf(chars[i]);

            if (Character.isDigit(chars[i])) {
                StringBuilder sb = new StringBuilder(item);

                while (i + 1 < chars.length && Character.isDigit(chars[i + 1]))
                    sb.append(chars[++i]);

                ls.add(sb.toString());
                ls.add("*");

                if (chars[i + 1] != '(') {
                    ls.add(String.valueOf(chars[++i]));
                    if (i + 1 < chars.length && chars[i + 1] != ')') {
                        ls.add("+");
                    }
                }
            } else {
                if (item.equals("(")) {
                    ls.add(item);
                } else if (item.equals(")")) {
                    ls.add(item);
                    if (i + 1 < chars.length && chars[i + 1] != ')')
                        ls.add("+");
                } else {
                    ls.add(item);
                    if (i + 1 < chars.length && chars[i + 1] != ')') {
                        ls.add("+");
                    }
                }
            }
        }
        return ls;
    }

    static List<String> toSuffixExpression(List<String> infixExpression) {
        Stack<String> stack = new Stack<>();
        List<String> suffix = new ArrayList<>();

        for (String s : infixExpression) {
            switch (s) {
                case "(":
                    stack.push("(");
                    break;

                case ")":
                    while (!stack.peek().equals("("))
                        suffix.add(stack.pop());
                    stack.pop();
                    break;

                default:
                    if (s.charAt(0) == '+' || s.charAt(0) == '*') {
                        if (stack.size() != 0 && operationPriority(stack.peek().charAt(0)) > operationPriority(s.charAt(0)))
                            suffix.add(stack.pop());
                        stack.push(s);
                    } else {
                        suffix.add(s);
                    }
                    break;
            }
        }
        while (stack.size() != 0)
            suffix.add(stack.pop());
        return suffix;
    }

    static String calculate(String c1, String c2, char opera) {
        if (opera == '+') {
            return c2 + c1;
        } else {
            int i = Integer.parseInt(c2);
            StringBuilder sb = new StringBuilder();
            while (i-- > 0)
                sb.append(c1);
            return sb.toString();
        }
    }

    static String calculate(List<String> suffixExpression) {
        Stack<String> stack = new Stack<>();
        for (String s : suffixExpression) {
            if (s.charAt(0) == '+' || s.charAt(0) == '*') {
                stack.push(calculate(stack.pop(), stack.pop(), s.charAt(0)));
            } else {
                stack.push(s);
            }
        }
        return stack.pop();
    }

    static String calculate(String expression) {
        return calculate(toSuffixExpression(toInfixExpression(expression)));
    }
}
```

一开始有地方写错了，后面改来改去导致代码有点乱。。

**Comment by whhcs** [comment]
> # 解法2
> 提供一种不用递归的方法 -- 当然，代码量会多一点
> 
> ## 思路
> 将输入的字符串看成一个表达式，将其转化成[中缀表达式](https://baike.baidu.com/item/%E4%B8%AD%E7%BC%80%E8%A1%A8%E8%BE%BE%E5%BC%8F)，再转成[逆波兰表达式](https://baike.baidu.com/item/%E9%80%86%E6%B3%A2%E5%85%B0%E5%BC%8F)（即后缀表达式），利用栈来解决问题。
> 
> ## 例子
> 以Sample Input 的第一个 `1(1a2b1(ab)1c)` 为例，将其转换成中缀表达式：
> 
> ```
> [1, *, (, 1, *, a, +, 2, *, b, +, 1, *, (, a, +, b, ), +, 1, *, c, )]
> ```
> 
> 则其后缀表达式就为：
> 
> ```
> [1, 1, a, *, 2, b, *, 1, a, b, +, *, 1, c, *, +, +, +, *]
> ```
> 
> ## 代码
> 我用的是Java，语法跟C++是差不多的...（看看有没有大佬写个C++版本<img alt="" width="20" height="20" src="https://camo.githubusercontent.com/54712f560a73f8f6c648788e21b0fb6d01ba623f039062a5f1ae36d04ce396fa/68747470733a2f2f696d672e77656e68616972752e636f6d2f696d616765732f323032302f31322f30312f574d5657742e706e67">）
> 
> ```java
> import java.util.*;
> 
> public class Main {
>     public static void main(String[] args) {
>         Scanner sc = new Scanner(System.in);
> 
>         int n = sc.nextInt();
>         while (n-- > 0)
>             System.out.println(calculate(sc.next()));
> 
>         sc.close();
>     }
> 
>     static int operationPriority(char opera) {
>         return opera == '*' ? 1 : 0;
>     }
> 
>     static List<String> toInfixExpression(String expression) {
>         List<String> ls = new ArrayList<>();
>         char[] chars = expression.toCharArray();
> 
>         for (int i = 0; i < chars.length; i++) {
>             String item = String.valueOf(chars[i]);
> 
>             if (Character.isDigit(chars[i])) {
>                 StringBuilder sb = new StringBuilder(item);
> 
>                 while (i + 1 < chars.length && Character.isDigit(chars[i + 1]))
>                     sb.append(chars[++i]);
> 
>                 ls.add(sb.toString());
>                 ls.add("*");
> 
>                 if (chars[i + 1] != '(') {
>                     ls.add(String.valueOf(chars[++i]));
>                     if (i + 1 < chars.length && chars[i + 1] != ')') {
>                         ls.add("+");
>                     }
>                 }
>             } else {
>                 if (item.equals("(")) {
>                     ls.add(item);
>                 } else if (item.equals(")")) {
>                     ls.add(item);
>                     if (i + 1 < chars.length && chars[i + 1] != ')')
>                         ls.add("+");
>                 } else {
>                     ls.add(item);
>                     if (i + 1 < chars.length && chars[i + 1] != ')') {
>                         ls.add("+");
>                     }
>                 }
>             }
>         }
>         return ls;
>     }
> 
>     static List<String> toSuffixExpression(List<String> infixExpression) {
>         Stack<String> stack = new Stack<>();
>         List<String> suffix = new ArrayList<>();
> 
>         for (String s : infixExpression) {
>             switch (s) {
>                 case "(":
>                     stack.push("(");
>                     break;
> 
>                 case ")":
>                     while (!stack.peek().equals("("))
>                         suffix.add(stack.pop());
>                     stack.pop();
>                     break;
> 
>                 default:
>                     if (s.charAt(0) == '+' || s.charAt(0) == '*') {
>                         if (stack.size() != 0 && operationPriority(stack.peek().charAt(0)) > operationPriority(s.charAt(0)))
>                             suffix.add(stack.pop());
>                         stack.push(s);
>                     } else {
>                         suffix.add(s);
>                     }
>                     break;
>             }
>         }
>         while (stack.size() != 0)
>             suffix.add(stack.pop());
>         return suffix;
>     }
> 
>     static String calculate(String c1, String c2, char opera) {
>         if (opera == '+') {
>             return c2 + c1;
>         } else {
>             int i = Integer.parseInt(c2);
>             StringBuilder sb = new StringBuilder();
>             while (i-- > 0)
>                 sb.append(c1);
>             return sb.toString();
>         }
>     }
> 
>     static String calculate(List<String> suffixExpression) {
>         Stack<String> stack = new Stack<>();
>         for (String s : suffixExpression) {
>             if (s.charAt(0) == '+' || s.charAt(0) == '*') {
>                 stack.push(calculate(stack.pop(), stack.pop(), s.charAt(0)));
>             } else {
>                 stack.push(s);
>             }
>         }
>         return stack.pop();
>     }
> 
>     static String calculate(String expression) {
>         return calculate(toSuffixExpression(toInfixExpression(expression)));
>     }
> }
> ```
> 
> 一开始有地方写错了，后面改来改去导致代码有点乱。。

**Comment by whhcs** [comment]
> # 解法2
> 提供一种不用递归的方法 -- 当然，代码量会多一点
> 
> ## 思路
> 将输入的字符串看成一个表达式，将其转化成[中缀表达式](https://baike.baidu.com/item/%E4%B8%AD%E7%BC%80%E8%A1%A8%E8%BE%BE%E5%BC%8F)，再转成[逆波兰表达式](https://baike.baidu.com/item/%E9%80%86%E6%B3%A2%E5%85%B0%E5%BC%8F)（即后缀表达式），利用栈来解决问题。
> 
> ## 例子
> 以Sample Input 的第一个 `1(1a2b1(ab)1c)` 为例，将其转换成中缀表达式：
> 
> ```
> [1, *, (, 1, *, a, +, 2, *, b, +, 1, *, (, a, +, b, ), +, 1, *, c, )]
> ```
> 
> 则其后缀表达式就为：
> 
> ```
> [1, 1, a, *, 2, b, *, 1, a, b, +, *, 1, c, *, +, +, +, *]
> ```
> 
> ## 代码
> 我用的是Java，语法跟C++是差不多的...（看看有没有大佬写个C++版本<img alt="" width="20" height="20" src="https://camo.githubusercontent.com/54712f560a73f8f6c648788e21b0fb6d01ba623f039062a5f1ae36d04ce396fa/68747470733a2f2f696d672e77656e68616972752e636f6d2f696d616765732f323032302f31322f30312f574d5657742e706e67">）
> 
> ```java
> import java.util.*;
> 
> public class Main {
>     public static void main(String[] args) {
>         Scanner sc = new Scanner(System.in);
> 
>         int n = sc.nextInt();
>         while (n-- > 0)
>             System.out.println(calculate(sc.next()));
> 
>         sc.close();
>     }
> 
>     static int operationPriority(char opera) {
>         return opera == '*' ? 1 : 0;
>     }
> 
>     static List<String> toInfixExpression(String expression) {
>         List<String> ls = new ArrayList<>();
>         char[] chars = expression.toCharArray();
> 
>         for (int i = 0; i < chars.length; i++) {
>             String item = String.valueOf(chars[i]);
> 
>             if (Character.isDigit(chars[i])) {
>                 StringBuilder sb = new StringBuilder(item);
> 
>                 while (i + 1 < chars.length && Character.isDigit(chars[i + 1]))
>                     sb.append(chars[++i]);
> 
>                 ls.add(sb.toString());
>                 ls.add("*");
> 
>                 if (chars[i + 1] != '(') {
>                     ls.add(String.valueOf(chars[++i]));
>                     if (i + 1 < chars.length && chars[i + 1] != ')') {
>                         ls.add("+");
>                     }
>                 }
>             } else {
>                 if (item.equals("(")) {
>                     ls.add(item);
>                 } else if (item.equals(")")) {
>                     ls.add(item);
>                     if (i + 1 < chars.length && chars[i + 1] != ')')
>                         ls.add("+");
>                 } else {
>                     ls.add(item);
>                     if (i + 1 < chars.length && chars[i + 1] != ')') {
>                         ls.add("+");
>                     }
>                 }
>             }
>         }
>         return ls;
>     }
> 
>     static List<String> toSuffixExpression(List<String> infixExpression) {
>         Stack<String> stack = new Stack<>();
>         List<String> suffix = new ArrayList<>();
> 
>         for (String s : infixExpression) {
>             switch (s) {
>                 case "(":
>                     stack.push("(");
>                     break;
> 
>                 case ")":
>                     while (!stack.peek().equals("("))
>                         suffix.add(stack.pop());
>                     stack.pop();
>                     break;
> 
>                 default:
>                     if (s.charAt(0) == '+' || s.charAt(0) == '*') {
>                         if (stack.size() != 0 && operationPriority(stack.peek().charAt(0)) > operationPriority(s.charAt(0)))
>                             suffix.add(stack.pop());
>                         stack.push(s);
>                     } else {
>                         suffix.add(s);
>                     }
>                     break;
>             }
>         }
>         while (stack.size() != 0)
>             suffix.add(stack.pop());
>         return suffix;
>     }
> 
>     static String calculate(String c1, String c2, char opera) {
>         if (opera == '+') {
>             return c2 + c1;
>         } else {
>             int i = Integer.parseInt(c2);
>             StringBuilder sb = new StringBuilder();
>             while (i-- > 0)
>                 sb.append(c1);
>             return sb.toString();
>         }
>     }
> 
>     static String calculate(List<String> suffixExpression) {
>         Stack<String> stack = new Stack<>();
>         for (String s : suffixExpression) {
>             if (s.charAt(0) == '+' || s.charAt(0) == '*') {
>                 stack.push(calculate(stack.pop(), stack.pop(), s.charAt(0)));
>             } else {
>                 stack.push(s);
>             }
>         }
>         return stack.pop();
>     }
> 
>     static String calculate(String expression) {
>         return calculate(toSuffixExpression(toInfixExpression(expression)));
>     }
> }
> ```
> 
> 一开始有地方写错了，后面改来改去导致代码有点乱。。

可以可以，等我有时间学了你说的什么中缀表达式、逆波兰表达式、栈什么的再重写一遍这道题

**Comment by SamuNatsu** [comment]
# Java convert to C++
```cpp
#include <cstdio>

#include <stack>
#include <string>
#include <vector>
#include <iostream>

int n;
std::string str;

// 原式转前缀表达式
std::vector<std::string> toInfix(const std::string& tmp) {
    std::vector<std::string> infix;
    // 扫描原式
    for (size_t i = 0; i < tmp.length(); ++i)
        // 处理数字
        if (isdigit(tmp[i])) {
            std::string buff(1, tmp[i]);
            while (i + 1 < tmp.length() && isdigit(str[i + 1]))
                buff += tmp[++i];
            infix.emplace_back(buff);
            infix.emplace_back("*");
            if (str.c_str()[i + 1] != '(') {
                infix.emplace_back(1, str.c_str()[++i]);
                if (i + 1 < tmp.length() && str[i + 1] != ')')
                    infix.emplace_back("+");
            }
        }
        // 处理非数字
        else {
            if (tmp[i] == '(')
                infix.emplace_back("(");
            else if (tmp[i] == ')') {
                infix.emplace_back(")");
                if (i + 1 < tmp.length() && tmp[i + 1] != ')')
                    infix.emplace_back("+");
            }
            else {
                infix.emplace_back(1, tmp[i]);
                if (i + 1 < tmp.length() && tmp[i + 1] != ')')
                    infix.emplace_back("+");
            }
        }
    return infix;
}

// 计算优先级
int priority(char tmp) {
    return tmp == '*' ? 1 : 0;
}

// 前缀表达式转后缀表达式
std::vector<std::string> toSuffix(const std::vector<std::string>& tmp) {
    std::stack<std::string> stk;
    std::vector<std::string> suffix;
    // 扫描前缀表达式
    for (auto &i : tmp)
        switch (i[0]) {
            case ('('):
                stk.push("(");
                break;
            case (')'):
                while (stk.top()[0] != '(') {
                    suffix.emplace_back(stk.top());
                    stk.pop();
                }
                stk.pop();
                break;
            default:
                if (i[0] == '+' || i[0] == '*') {
                    if (stk.size() && priority(stk.top()[0]) > priority(i[0])) {
                        suffix.emplace_back(stk.top());
                        stk.pop();
                    }
                    stk.push(i);
                }
                else
                    suffix.emplace_back(i);
                break;
        }
    while (stk.size()) {
        suffix.emplace_back(stk.top());
        stk.pop();
    }
    return suffix;
}

// std::string转int
int toInt(const std::string& tmp) {
    int rtn;
    sscanf(tmp.c_str(), "%d", &rtn);
    return rtn;
}

// 计算
std::string mk(const std::string& s1, const std::string& s2, char op) {
    // 处理+
    if (op == '+')
        return s2 + s1;
    // 处理*
    else {
        std::string buff;
        // 将字符串转换为整数
        int i = toInt(s2);
        while (i--)
            buff += s1;
        return buff;
    }
}

// 计算答案
std::string calculate() {
    // 获取后缀表达式
    std::vector<std::string> suffix = toSuffix(toInfix(str));
    // 运算数栈
    std::stack<std::string> stk;
    // 扫描表达式
    for (auto &i : suffix)
        // 对运算符进行处理
        if (i[0] == '+' || i[0] == '*') {
            // 取运算数
            std::string s1, s2;
            s1 = stk.top();
            stk.pop();
            s2 = stk.top();
            stk.pop();
            // 将运算结果入栈
            stk.push(mk(s1, s2, i[0]));
        }
        // 不是运算符则将运算数入栈
        else
            stk.push(i);
    // 最终栈顶元素就是运算结果
    return stk.top();
}

// 主函数
int main() {
    // 取消与C标准IO的同步，加速C++标准IO
    std::ios::sync_with_stdio(false);
    // 读入数据组数
    std::cin >> n;
    // 对于每组数据
    while (n--) {
        // 读入字符串
        std::cin >> str;
        // 输出答案
        std::cout << calculate() << std::endl;
    }
    return 0;
}
```
