### ISSUE TITLE
2020-12 POJ1664：分苹果-解题报告（叶子豪）

### ISSUE THREAD

**Issue by 202002020325** [CSGrandeur/s-1problem1day1ac#6]
### 题目大意
原题目：把M个同样的苹果放在N个同样的盘子里，允许有的盘子空着不放，问共有多少种不同的分法？（用K表示）5，1，1和1，5，1 是同一种分法。
题目理解：将M个相同的苹果分堆，最多可分为N堆，即将M个苹果分为1，2，3......N堆的情况相加即可，且每堆不分先后。
### 解题思路
根据题目理解，我们需先逐个计算M个苹果分为1，2......N堆的情况。我们从后往前考虑，先将M个苹果分为N堆，先假定M>N，那么要放满所有盘子（即N个）的话，不妨先将每个盘子各放一个苹果，此时我们还剩下（M-N）个苹果要放入N个盘子中，且可以不放满。不难发现，这种情况就是（M-N）个苹果放在N个盘子里，允许有的盘子空着不放，刚刚好回到题目，即可以进行一次递归。那么此时我们仅仅计算了将M个苹果放满于N个盘子中，还需计算M个苹果放于（N-1）个盘子中有几种放法。即将M个苹果放在N个盘子里的放法等于（M-N）个苹果放在N个盘子里的放法和M个苹果放在（N-1）个苹果的放法。此时M>N。
那么M=N时情况就变得更加可观，M个苹果放满于N个盘子的放法仅一种，所以此时M个苹果放在N个盘子的放法等于1+（M个苹果放在（N-1）个苹果的放法）。
那么M<N时，苹果永远都放不满盘子，由于盘子全都是一样的，那么我们可以丢弃一部分盘子，使得盘子总数等于苹果数，那么我们又回到了M=N的情况。
使用动态规划时，我们不再使用return，我们使用二维数组a[M][N]来储存数据。使用return时，我们可以理解为return a[m][n] = divide_apples(m,n-1) +divide_apples(m-n,n)（取部分情况，详情看如下代码），相当于a[m][m] = a[m][n-1] + a[m-n,n]。其它同理。
### 复杂度分析
使用递归时，f(m, n) 对应的计算量，最差的情况是f(m,n)≤f(m,n-1)+f(m-n,n)。无论怎样都会要么m少1，要么n少1，所以最差一共有（m+n）层，所以空间复杂度为O(2^n)。而由于在计算推导的时候并不会出现分叉，故时间复杂度为O（n）。
使用动态规划后，可以发现有一个for循环嵌套在另一个for循环里面，而一个for循环的复杂度为O（n），因此可以得出时间复杂度为O（n^2），空间复杂度也为O（n^2）。
### 算法资料与心得体会
算法与 http://blog.sina.com.cn/s/blog_b1e4dca501014476.html 相似，思路基本一致。
初看题目，我们注意到N个盘子和N-1个盘子是有一定的关系，因此我们使用递归的方法。我们要找的是根据之前的放法，来推导出现在的放法有几种。由题目了解到到它是可以不放满的，那么我们就讨论放一个，放两个，一直到放N个的情况有多少种，到这一步，基本可以发现规律了，但注意到此时M应该是≥N的，然后就可以分类讨论寻找其中的规律。遇到这种题找不到公式来推出相应结果时，应该冷静下来，考虑是否跟之前的数据有关系，然后找出关系，使用递归逐个求解。例如讨论M>N时，返回divide_apples(m,n-1)+divide_apples(m-n,n)时，前面的divide_apples(m,n-1)不是这么容易想到的，很多人（包括我）一开始尝试有没有什么公式可以计算M个苹果放满N个盘子的放法数，但是耗费了很多时间，发现几乎没有什么公式或者规律来计算，此时，我们应该尝试找找与前面的关系，否则我们只会一直做无用功。
### 代码
```C
#include <stdio.h>
int divide_apples (int m, int n)
{
    if (n == 1  ||  m == 1) return 1;//只一个盘子或只有一个苹果的放法明显只有一种 
    
	else if (n > m) return divide_apples(m,m);//根据上面解题思路进行一个递归 
    
	else if (n == m) return 1+divide_apples(m,n-1);
    
	else if (n < m) return divide_apples(m,n-1)+divide_apples(m-n,n);
}
int main()
{
    int t, N, M, K;
    
	scanf("%d", &t);//由于题目需要输测试数据的数目，根据题目要求，写出基本框架 
    
	while (t--)
	{
        scanf("%d %d", &M, &N);
        
		K = divide_apples(M,N);//利用上面函数，给其进行赋值并打印出来 
        
		printf("%d", K);
        
		printf("\n"); 
    }
    return 0;
}
```
使用动态规划后
```C
#include <stdio.h>
#include <string.h> 
int main(){
	int m, n;
	
	int t, N, M, K;
	
	int a[11][11];
	
    scanf("%d", &t);
    
    while (t--)
	{
        scanf("%d %d",&M,&N);
        
        for (m=1; m <= M; m++)
		{
    	for (n = 1; n <= N; n++)
		{
    		if (m == 1 || n == 1)
			{
    			a[m][n] = 1;
    			}
    			
    		else{
    			if (m == n) a[m][n] = 1 + a[m][n-1];
				else if (m < n) a[m][n] = a[m][m];
				
else if (m > n) a[m][n] = a[m][n-1] + a[m-n][n];	
			}
		}
	}
        K = a[M][N];
        printf("%d\n", K);
    }
    return 0;
}
```

**Comment by SamuNatsu** [comment]
提供一种更加简单直观的做法
本质就是常规的递归搜索加剪枝操作

由题可知5,1,1和1,5,1是同一种分法，所以我们可以干脆限制第N个盘最多分得的苹果必须小于等于第N-1个盘子，也就是让盘子之间的苹果数量保证递减就行了
所以使用dfs搜索，k表示当前正在为第k个盘子分苹果，l表示剩下l个苹果没有分，lst表示第k-1个盘子分得了lst个苹果
如果k>N了且苹果已经分完（l==0），那么我们视为找到了一种合理分法，否则返回
至于为什么要使用min(l,lst)，这是为了保证在有苹果可分的情况下使得盘子间苹果数量递减

```cpp
#include <cstdio>

#include <algorithm>

int t, M, N, tot;

void dfs(int k, int l, int lst) {
    if (k > N) {
        if (l == 0)
            ++tot;
        return;
    }
    for (int i = std::min(l, lst); i >= 0; --i)
        dfs(k + 1, l - i, i);
}

int main() {
    scanf("%d", &t);
    while (t--) {
        scanf("%d%d", &M, &N);
        tot = 0;
        dfs(1, M, 0x7FFFFFFF);
        printf("%d\n", tot);
    }
    return 0;
}
```

**Comment by Simon-Veen** [comment]
如007，016，025，034，115，124，133，223这就是例子的所有情况，
考虑到每个盘子放苹果数是不能重复的，那么就以递增式的方法放苹果，
其实对于一个题目，先把答案枚举出来，再通过观察，就能思考出规律。

`#include<cstdio>
int m, n, cnt;
void dfs(int k, int v, int p)
{
    if(v == n)
    {
        if(k == m)cnt++;
        return;
    }
    for(int i = p; i <= m; i++)
        dfs(i + k, v + 1, i);
}
int main()
{
    int t;
    scanf("%d", &t);
    while(t--)
    {
        cnt = 0;
        scanf("%d%d", &m, &n);
        dfs(0, 0, 0);
        printf("%d\n", cnt);
    }
} `

**Comment by Simon-Veen** [comment]
可以先分析下样例，枚举答案得
007 016 025 034 115 124 133 223
观察得到这是不下降式的递增过程，由此可以暴力枚举得到答案
```
#include<cstdio>
int m, n, cnt;
void dfs(int k, int v, int p)
{
    if(v == n)
    {
        if(k == m)cnt++;
        return;
    }
    for(int i = p; i <= m; i++)
        dfs(i + k, v + 1, i);
}
int main()
{
    int t;
    scanf("%d", &t);
    while(t--)
    {
        cnt = 0;
        scanf("%d%d", &m, &n);
        dfs(0, 0, 0);
        printf("%d\n", cnt);
    }
}

```

**Comment by Simon-Veen** [comment]
可以先分析下样例，枚举答案得
007 016 025 034 115 124 133 223
观察得到这是不下降式的递增过程，由此可以暴力枚举得到答案

```cpp
#include<cstdio>
int m, n, cnt;
void dfs(int k, int v, int p)
{
    if(v == n)
    {
        if(k == m)cnt++;
        return;
    }
    for(int i = p; i <= m; i++)
        dfs(i + k, v + 1, i);
}
int main()
{
    int t;
    scanf("%d", &t);
    while(t--)
    {
        cnt = 0;
        scanf("%d%d", &m, &n);
        dfs(0, 0, 0);
        printf("%d\n", cnt);
    }
}
```
